# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 610)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color:rgba(255,255,255,255)")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(280, 280, 491, 80))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#0e659a;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(170, 200, 691, 80))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#0e659a;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(80, 380, 441, 171))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#0e659a;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(370, 20, 511, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:#0e659a;\n"
"\n"
"padding-bottom:7px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(370, 100, 521, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#0e659a;")
        self.label_7.setObjectName("label_7")
        self.start = QtWidgets.QPushButton(self.widget)
        self.start.setGeometry(QtCore.QRect(600, 480, 190, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("\n"
"\n"
"QPushButton#start{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#start:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#start:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 40, 100, 100))
        self.label.setStyleSheet("image: url(:/icon/download.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/download.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(170, 50, 100, 100))
        self.label_2.setStyleSheet("image: url(:/icon/download (1).png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/download (1).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ĐỒ ÁN ROBOT FANUC"))
        self.label_4.setText(_translate("MainWindow", "BÁO CÁO ĐỒ ÁN KỸ THUẬT ROBOT"))
        self.label_5.setText(_translate("MainWindow", "GVHD: TS. Đặng Xuân Ba \n"
"SVTH:  Trương Quang Trường   20151425\n"
"           Lý Đắc Vinh                 20151430\n"
"           Nguyễn Quang Trường  20151424\n"
"           Nguyễn Minh Đăng       20151353"))
        self.label_6.setText(_translate("MainWindow", "TRƯỜNG ĐẠI HỌC\n"
"SƯ PHẠM KỸ THUẬT TP.HCM "))
        self.label_7.setText(_translate("MainWindow", "BỘ MÔN TỰ ĐỘNG ĐIỀU KHIỂN \n"
"KHOA ĐIỆN - ĐIỆN TỬ"))
        self.start.setText(_translate("MainWindow", "START"))
import pic_rc
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
