# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Display1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-20, 0, 1281, 831))
        self.widget.setStyleSheet("background-color:rgba(255,255,255,255);")
        self.widget.setObjectName("widget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 60, 1011, 651))
        self.stackedWidget.setStyleSheet("background-color:rgba(255,255,255,255);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.login = QtWidgets.QWidget(self.page_login)
        self.login.setGeometry(QtCore.QRect(0, -20, 1011, 671))
        self.login.setStyleSheet("background-color:rgba(255,255,255,255)")
        self.login.setObjectName("login")
        self.label_16 = QtWidgets.QLabel(self.login)
        self.label_16.setGeometry(QtCore.QRect(250, 360, 541, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:#0e659a;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.login)
        self.label_17.setGeometry(QtCore.QRect(90, 280, 851, 80))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:#0e659a;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.login)
        self.label_18.setGeometry(QtCore.QRect(50, 470, 441, 171))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:#0e659a;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.login)
        self.label_19.setGeometry(QtCore.QRect(380, 50, 571, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:#0e659a;\n"
"\n"
"padding-bottom:7px;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.login)
        self.label_20.setGeometry(QtCore.QRect(390, 140, 521, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:#0e659a;")
        self.label_20.setObjectName("label_20")
        self.start = QtWidgets.QPushButton(self.login)
        self.start.setGeometry(QtCore.QRect(670, 550, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("\n"
"\n"
"QPushButton#start{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#start:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#start:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.start.setObjectName("start")
        self.label_21 = QtWidgets.QLabel(self.login)
        self.label_21.setGeometry(QtCore.QRect(120, 50, 131, 171))
        self.label_21.setStyleSheet("image: url(:/icon/download.png);")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/icon/icon/download.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.stackedWidget.addWidget(self.page_login)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.Display_setting = QtWidgets.QWidget(self.page_setting)
        self.Display_setting.setGeometry(QtCore.QRect(0, 0, 1011, 651))
        self.Display_setting.setStyleSheet("background-color:rgba(255,255,255,255)")
        self.Display_setting.setObjectName("Display_setting")
        self.label_15 = QtWidgets.QLabel(self.Display_setting)
        self.label_15.setGeometry(QtCore.QRect(290, 440, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_6 = QtWidgets.QLabel(self.Display_setting)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 351, 251))
        self.label_6.setStyleSheet("background-image: url(\"E:/STUDY/KY 7/DO_AN_TT_ROBOT/CODE_PYTHON/DANG_GUI/icon/mega.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icon/mega.png"))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.Display_setting)
        self.label_10.setGeometry(QtCore.QRect(530, 120, 55, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Display_setting)
        self.label_11.setGeometry(QtCore.QRect(600, 80, 361, 261))
        self.label_11.setStyleSheet("background-image: url(\"E:/STUDY/KY 7/DO_AN_TT_ROBOT/CODE_PYTHON/DANG_GUI/icon/PC_LAP.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("icon/PC_LAP.png"))
        self.label_11.setObjectName("label_11")
        self.Arrow_vinh = QtWidgets.QLabel(self.Display_setting)
        self.Arrow_vinh.setGeometry(QtCore.QRect(440, 170, 111, 71))
        self.Arrow_vinh.setStyleSheet("")
        self.Arrow_vinh.setText("")
        self.Arrow_vinh.setObjectName("Arrow_vinh")
        self.frame_3 = QtWidgets.QFrame(self.Display_setting)
        self.frame_3.setGeometry(QtCore.QRect(30, 410, 721, 237))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_9)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(" border: 1px solid black;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.Port_2 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Port_2.setFont(font)
        self.Port_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Port_2.setStyleSheet("")
        self.Port_2.setEditable(True)
        self.Port_2.setCurrentText("")
        self.Port_2.setObjectName("Port_2")
        self.horizontalLayout_2.addWidget(self.Port_2)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(" border: 1px solid black;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.Baudrate_2 = QtWidgets.QComboBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Baudrate_2.setFont(font)
        self.Baudrate_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Baudrate_2.setStyleSheet("")
        self.Baudrate_2.setEditable(True)
        self.Baudrate_2.setObjectName("Baudrate_2")
        self.Baudrate_2.addItem("")
        self.horizontalLayout_4.addWidget(self.Baudrate_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_9)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CONNECT = QtWidgets.QPushButton(self.frame_7)
        self.CONNECT.setMinimumSize(QtCore.QSize(100, 50))
        self.CONNECT.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CONNECT.setFont(font)
        self.CONNECT.setStyleSheet("\n"
"\n"
"QPushButton#CONNECT{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#CONNECT:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#CONNECT:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.CONNECT.setObjectName("CONNECT")
        self.verticalLayout_2.addWidget(self.CONNECT)
        self.DISCONNECT = QtWidgets.QPushButton(self.frame_7)
        self.DISCONNECT.setMinimumSize(QtCore.QSize(0, 50))
        self.DISCONNECT.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DISCONNECT.setFont(font)
        self.DISCONNECT.setStyleSheet("\n"
"\n"
"QPushButton#DISCONNECT{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#DISCONNECT:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#DISCONNECT:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.DISCONNECT.setObjectName("DISCONNECT")
        self.verticalLayout_2.addWidget(self.DISCONNECT)
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_9)
        self.label_31 = QtWidgets.QLabel(self.Display_setting)
        self.label_31.setGeometry(QtCore.QRect(20, 390, 981, 20))
        self.label_31.setStyleSheet("background-color: #8E8D8A;")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.stackedWidget.addWidget(self.page_setting)
        self.page_Manual = QtWidgets.QWidget()
        self.page_Manual.setObjectName("page_Manual")
        self.Display_Manual = QtWidgets.QWidget(self.page_Manual)
        self.Display_Manual.setGeometry(QtCore.QRect(0, 0, 1011, 651))
        self.Display_Manual.setStyleSheet("background-color:rgba(255,255,255,255);")
        self.Display_Manual.setObjectName("Display_Manual")
        self.groupBox = QtWidgets.QGroupBox(self.Display_Manual)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 281, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(85, 170, 255);\n"
"border: 1px solid black;\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.widget_13 = QtWidgets.QWidget(self.groupBox)
        self.widget_13.setGeometry(QtCore.QRect(12, 33, 92, 246))
        self.widget_13.setObjectName("widget_13")
        self.label_2 = QtWidgets.QLabel(self.widget_13)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 70, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_13)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 70, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_13)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 70, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setGeometry(QtCore.QRect(111, 33, 158, 246))
        self.widget_2.setObjectName("widget_2")
        self.theta1 = QtWidgets.QLineEdit(self.widget_2)
        self.theta1.setGeometry(QtCore.QRect(11, 36, 131, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theta1.setFont(font)
        self.theta1.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"\n"
"padding-bottom:7px;")
        self.theta1.setAlignment(QtCore.Qt.AlignCenter)
        self.theta1.setObjectName("theta1")
        self.theta2 = QtWidgets.QLineEdit(self.widget_2)
        self.theta2.setGeometry(QtCore.QRect(11, 104, 131, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theta2.setFont(font)
        self.theta2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.theta2.setAlignment(QtCore.Qt.AlignCenter)
        self.theta2.setObjectName("theta2")
        self.theta3 = QtWidgets.QLineEdit(self.widget_2)
        self.theta3.setGeometry(QtCore.QRect(11, 172, 131, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theta3.setFont(font)
        self.theta3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.theta3.setAlignment(QtCore.Qt.AlignCenter)
        self.theta3.setObjectName("theta3")
        self.label_23 = QtWidgets.QLabel(self.widget_2)
        self.label_23.setGeometry(QtCore.QRect(100, 10, 47, 13))
        self.label_23.setObjectName("label_23")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Display_Manual)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 330, 281, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(85, 170, 255);\n"
"border: 1px solid black;\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget_15 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_15.setGeometry(QtCore.QRect(12, 20, 91, 276))
        self.widget_15.setObjectName("widget_15")
        self.label_7 = QtWidgets.QLabel(self.widget_15)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_15)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_15)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 72, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.widget_16 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_16.setGeometry(QtCore.QRect(108, 20, 161, 276))
        self.widget_16.setObjectName("widget_16")
        self.Px = QtWidgets.QLineEdit(self.widget_16)
        self.Px.setGeometry(QtCore.QRect(11, 44, 134, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Px.setFont(font)
        self.Px.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"\n"
"padding-bottom:7px;")
        self.Px.setAlignment(QtCore.Qt.AlignCenter)
        self.Px.setObjectName("Px")
        self.Py = QtWidgets.QLineEdit(self.widget_16)
        self.Py.setGeometry(QtCore.QRect(11, 120, 134, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Py.setFont(font)
        self.Py.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.Py.setAlignment(QtCore.Qt.AlignCenter)
        self.Py.setObjectName("Py")
        self.Pz = QtWidgets.QLineEdit(self.widget_16)
        self.Pz.setGeometry(QtCore.QRect(10, 200, 134, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Pz.setFont(font)
        self.Pz.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.Pz.setAlignment(QtCore.Qt.AlignCenter)
        self.Pz.setObjectName("Pz")
        self.label_24 = QtWidgets.QLabel(self.widget_16)
        self.label_24.setGeometry(QtCore.QRect(110, 10, 47, 13))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.widget_3 = QtWidgets.QWidget(self.Display_Manual)
        self.widget_3.setGeometry(QtCore.QRect(310, 450, 691, 191))
        self.widget_3.setStyleSheet("border: 1px solid ;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.Return_box = QtWidgets.QPushButton(self.widget_3)
        self.Return_box.setGeometry(QtCore.QRect(20, 70, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Return_box.setFont(font)
        self.Return_box.setStyleSheet("\n"
"\n"
"QPushButton#Return_box{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#Return_box:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#Return_box:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.Return_box.setObjectName("Return_box")
        self.forward = QtWidgets.QPushButton(self.widget_3)
        self.forward.setGeometry(QtCore.QRect(20, 140, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.forward.setFont(font)
        self.forward.setStyleSheet("\n"
"\n"
"QPushButton#forward{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#forward:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#forward:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.forward.setObjectName("forward")
        self.Run = QtWidgets.QPushButton(self.widget_3)
        self.Run.setGeometry(QtCore.QRect(200, 70, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Run.setFont(font)
        self.Run.setStyleSheet("\n"
"\n"
"QPushButton#Run{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#Run:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#Run:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.Run.setObjectName("Run")
        self.Inverse = QtWidgets.QPushButton(self.widget_3)
        self.Inverse.setGeometry(QtCore.QRect(200, 140, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Inverse.setFont(font)
        self.Inverse.setStyleSheet("\n"
"\n"
"QPushButton#Inverse{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#Inverse:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#Inverse:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.Inverse.setObjectName("Inverse")
        self.Calc = QtWidgets.QPushButton(self.widget_3)
        self.Calc.setGeometry(QtCore.QRect(380, 70, 160, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Calc.setFont(font)
        self.Calc.setStyleSheet("\n"
"\n"
"QPushButton#Calc{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#attract:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#Calc:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.Calc.setObjectName("Calc")
        self.clear_row = QtWidgets.QPushButton(self.widget_3)
        self.clear_row.setGeometry(QtCore.QRect(380, 140, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_row.setFont(font)
        self.clear_row.setStyleSheet("\n"
"\n"
"QPushButton#clear_row{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#clear_row:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#clear_row:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.clear_row.setObjectName("clear_row")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Mode = QtWidgets.QLineEdit(self.widget_3)
        self.Mode.setGeometry(QtCore.QRect(120, 20, 91, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mode.setFont(font)
        self.Mode.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"\n"
"padding-bottom:7px;")
        self.Mode.setAlignment(QtCore.Qt.AlignCenter)
        self.Mode.setObjectName("Mode")
        self.Mic = QtWidgets.QPushButton(self.widget_3)
        self.Mic.setGeometry(QtCore.QRect(580, 90, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Mic.setFont(font)
        self.Mic.setStyleSheet("\n"
"\n"
"\n"
"QPushButton#Mic{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"image: url(:/icon/mic (1).svg);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"\n"
"QPushButton#Mic:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#Mic:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.Mic.setText("")
        self.Mic.setIconSize(QtCore.QSize(40, 40))
        self.Mic.setObjectName("Mic")
        self.reset = QtWidgets.QPushButton(self.widget_3)
        self.reset.setGeometry(QtCore.QRect(280, 20, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setStyleSheet("\n"
"\n"
"QPushButton#reset{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#Set_home:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#reset:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.reset.setObjectName("reset")
        self.frame_2 = QtWidgets.QFrame(self.Display_Manual)
        self.frame_2.setGeometry(QtCore.QRect(310, 50, 691, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 641, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Screen_diagram = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Screen_diagram.setContentsMargins(0, 0, 0, 0)
        self.Screen_diagram.setSpacing(0)
        self.Screen_diagram.setObjectName("Screen_diagram")
        self.table_the = QtWidgets.QTableWidget(self.frame_2)
        self.table_the.setGeometry(QtCore.QRect(190, 50, 321, 201))
        self.table_the.setObjectName("table_the")
        self.table_the.setColumnCount(3)
        self.table_the.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_the.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_the.setItem(4, 2, item)
        self.manual_auto = QtWidgets.QWidget(self.Display_Manual)
        self.manual_auto.setGeometry(QtCore.QRect(470, 0, 321, 61))
        self.manual_auto.setObjectName("manual_auto")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.manual_auto)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mode_manual = QtWidgets.QPushButton(self.manual_auto)
        self.mode_manual.setMaximumSize(QtCore.QSize(300, 30))
        self.mode_manual.setStyleSheet("\n"
"\n"
"QPushButton#mode_manual{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#mode_manual:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#mode_manual:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.mode_manual.setObjectName("mode_manual")
        self.horizontalLayout.addWidget(self.mode_manual)
        self.mode_auto = QtWidgets.QPushButton(self.manual_auto)
        self.mode_auto.setMaximumSize(QtCore.QSize(300, 30))
        self.mode_auto.setStyleSheet("\n"
"QPushButton#mode_auto{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#mode_auto:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#mode_auto:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.mode_auto.setObjectName("mode_auto")
        self.horizontalLayout.addWidget(self.mode_auto)
        self.frame_led = QtWidgets.QFrame(self.Display_Manual)
        self.frame_led.setGeometry(QtCore.QRect(830, 10, 131, 37))
        self.frame_led.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_led.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_led.setObjectName("frame_led")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_led)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.led_manual = QtWidgets.QLabel(self.frame_led)
        self.led_manual.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid black;\n"
"background-color: gray")
        self.led_manual.setText("")
        self.led_manual.setObjectName("led_manual")
        self.horizontalLayout_5.addWidget(self.led_manual)
        self.led_auto = QtWidgets.QLabel(self.frame_led)
        self.led_auto.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid black;\n"
"background-color: gray")
        self.led_auto.setText("")
        self.led_auto.setObjectName("led_auto")
        self.horizontalLayout_5.addWidget(self.led_auto)
        self.led_on_off = QtWidgets.QLabel(self.frame_led)
        self.led_on_off.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid black;\n"
"background-color: gray")
        self.led_on_off.setText("")
        self.led_on_off.setObjectName("led_on_off")
        self.horizontalLayout_5.addWidget(self.led_on_off)
        self.stackedWidget.addWidget(self.page_Manual)
        self.page_graph = QtWidgets.QWidget()
        self.page_graph.setObjectName("page_graph")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_graph)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 991, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Screen_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Screen_graph.setContentsMargins(0, 0, 0, 0)
        self.Screen_graph.setSpacing(0)
        self.Screen_graph.setObjectName("Screen_graph")
        self.stackedWidget.addWidget(self.page_graph)
        self.page_cam = QtWidgets.QWidget()
        self.page_cam.setObjectName("page_cam")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_cam)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 281, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(85, 170, 255);\n"
"border: 1px solid black;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget_19 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_19.setGeometry(QtCore.QRect(12, 33, 91, 291))
        self.widget_19.setObjectName("widget_19")
        self.label_26 = QtWidgets.QLabel(self.widget_19)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_22 = QtWidgets.QLabel(self.widget_19)
        self.label_22.setGeometry(QtCore.QRect(10, 130, 72, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.widget_19)
        self.label_25.setGeometry(QtCore.QRect(10, 210, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.widget_20 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_20.setGeometry(QtCore.QRect(108, 33, 161, 291))
        self.widget_20.setObjectName("widget_20")
        self.Px_cam = QtWidgets.QLineEdit(self.widget_20)
        self.Px_cam.setGeometry(QtCore.QRect(11, 44, 134, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Px_cam.setFont(font)
        self.Px_cam.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"\n"
"padding-bottom:7px;")
        self.Px_cam.setAlignment(QtCore.Qt.AlignCenter)
        self.Px_cam.setObjectName("Px_cam")
        self.Py_cam = QtWidgets.QLineEdit(self.widget_20)
        self.Py_cam.setGeometry(QtCore.QRect(11, 120, 134, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Py_cam.setFont(font)
        self.Py_cam.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.Py_cam.setAlignment(QtCore.Qt.AlignCenter)
        self.Py_cam.setObjectName("Py_cam")
        self.Pz_cam = QtWidgets.QLineEdit(self.widget_20)
        self.Pz_cam.setGeometry(QtCore.QRect(10, 200, 134, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Pz_cam.setFont(font)
        self.Pz_cam.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.Pz_cam.setAlignment(QtCore.Qt.AlignCenter)
        self.Pz_cam.setObjectName("Pz_cam")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_cam)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 281, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(85, 170, 255);\n"
"border: 1px solid black;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.set_robot = QtWidgets.QPushButton(self.groupBox_4)
        self.set_robot.setGeometry(QtCore.QRect(60, 40, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.set_robot.setFont(font)
        self.set_robot.setStyleSheet("\n"
"\n"
"QPushButton#set_robot{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#set_robot:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#set_robot:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.set_robot.setObjectName("set_robot")
        self.start_cam = QtWidgets.QPushButton(self.groupBox_4)
        self.start_cam.setGeometry(QtCore.QRect(60, 160, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_cam.setFont(font)
        self.start_cam.setStyleSheet("\n"
"\n"
"QPushButton#start_cam{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#start_cam:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#start_cam:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.start_cam.setObjectName("start_cam")
        self.send_cam = QtWidgets.QPushButton(self.groupBox_4)
        self.send_cam.setGeometry(QtCore.QRect(60, 100, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.send_cam.setFont(font)
        self.send_cam.setStyleSheet("\n"
"\n"
"QPushButton#send_cam{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#send_cam:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#send_cam:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.send_cam.setObjectName("send_cam")
        self.stop = QtWidgets.QPushButton(self.groupBox_4)
        self.stop.setGeometry(QtCore.QRect(60, 220, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("\n"
"\n"
"QPushButton#stop{\n"
"\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(10, 90, 190, 229), stop: 1 rgba(85, 98, 112,\n"
"\n"
"226));\n"
"\n"
"color:rgba(255, 255, 255, 210);\n"
"\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton#stop:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84,\n"
"\n"
"226));\n"
"}\n"
"\n"
"QPushButton#stop:pressed{\n"
"\n"
"padding-left:5px;\n"
"\n"
"padding-top:5px;\n"
" background-color:rgba(150, 123, 111, 255);\n"
"}`\n"
"")
        self.stop.setObjectName("stop")
        self.screen_cam = QtWidgets.QLabel(self.page_cam)
        self.screen_cam.setGeometry(QtCore.QRect(300, 10, 691, 631))
        self.screen_cam.setStyleSheet("border: 1px solid black;")
        self.screen_cam.setText("")
        self.screen_cam.setObjectName("screen_cam")
        self.stackedWidget.addWidget(self.page_cam)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(40, 10, 1101, 51))
        self.widget_4.setStyleSheet("background-color:  #0e71aa;\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(420, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(40, 60, 91, 651))
        self.frame.setStyleSheet("background-color:  #0e71aa;\n"
"\n"
"border-bottom-left-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Menu = QtWidgets.QToolButton(self.frame)
        self.Menu.setGeometry(QtCore.QRect(20, 20, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Menu.setFont(font)
        self.Menu.setStyleSheet("url:/icon/icons8-news-feed-48.png")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icons8-news-feed-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.setIcon(icon)
        self.Menu.setIconSize(QtCore.QSize(35, 35))
        self.Menu.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Menu.setObjectName("Menu")
        self.Setting = QtWidgets.QToolButton(self.frame)
        self.Setting.setGeometry(QtCore.QRect(20, 120, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Setting.setFont(font)
        self.Setting.setStyleSheet("url: /icon/icons8-settings-50 (1).png")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/icons8-settings-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Setting.setIcon(icon1)
        self.Setting.setIconSize(QtCore.QSize(35, 35))
        self.Setting.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Setting.setObjectName("Setting")
        self.Manual = QtWidgets.QToolButton(self.frame)
        self.Manual.setGeometry(QtCore.QRect(20, 180, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Manual.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/icons8-robotic-arm-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Manual.setIcon(icon2)
        self.Manual.setIconSize(QtCore.QSize(35, 35))
        self.Manual.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Manual.setObjectName("Manual")
        self.graph = QtWidgets.QToolButton(self.frame)
        self.graph.setGeometry(QtCore.QRect(20, 240, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.graph.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/icons8-graph-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graph.setIcon(icon3)
        self.graph.setIconSize(QtCore.QSize(35, 35))
        self.graph.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.graph.setObjectName("graph")
        self.Camera = QtWidgets.QToolButton(self.frame)
        self.Camera.setGeometry(QtCore.QRect(20, 300, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Camera.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Camera.setIcon(icon4)
        self.Camera.setIconSize(QtCore.QSize(35, 35))
        self.Camera.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Camera.setObjectName("Camera")
        self.Home = QtWidgets.QToolButton(self.frame)
        self.Home.setGeometry(QtCore.QRect(20, 70, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Home.setFont(font)
        self.Home.setStyleSheet("url: /icon/icons8-settings-50 (1).png")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home.setIcon(icon5)
        self.Home.setIconSize(QtCore.QSize(35, 35))
        self.Home.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Home.setObjectName("Home")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FANUC ROBOT"))
        self.label_16.setText(_translate("MainWindow", "ĐỒ ÁN ROBOT FANUC"))
        self.label_17.setText(_translate("MainWindow", "BÁO CÁO ĐỒ ÁN KỸ THUẬT ROBOT"))
        self.label_18.setText(_translate("MainWindow", "GVHD: TS. Đặng Xuân Ba \n"
"SVTH:  Trương Quang Trường   20151425\n"
"           Lý Đắc Vinh                   20151430\n"
"           Nguyễn Quang Trường   20151424\n"
"           Nguyễn Minh Đăng        20151353"))
        self.label_19.setText(_translate("MainWindow", "TRƯỜNG ĐẠI HỌC\n"
"SƯ PHẠM KỸ THUẬT TP.HCM "))
        self.label_20.setText(_translate("MainWindow", "BỘ MÔN TỰ ĐỘNG ĐIỀU KHIỂN \n"
"KHOA ĐIỆN - ĐIỆN TỬ"))
        self.start.setText(_translate("MainWindow", "START"))
        self.label_12.setText(_translate("MainWindow", "Connection status:"))
        self.label_13.setText(_translate("MainWindow", "Port:"))
        self.label_14.setText(_translate("MainWindow", "Baudrate:"))
        self.Baudrate_2.setCurrentText(_translate("MainWindow", "115200"))
        self.Baudrate_2.setItemText(0, _translate("MainWindow", "115200"))
        self.CONNECT.setText(_translate("MainWindow", "CONNECT"))
        self.DISCONNECT.setText(_translate("MainWindow", "DISCONNECT"))
        self.groupBox.setTitle(_translate("MainWindow", "Prameter Of Joints"))
        self.label_2.setText(_translate("MainWindow", "Theta3"))
        self.label_3.setText(_translate("MainWindow", "Theta2"))
        self.label_4.setText(_translate("MainWindow", "Theta1"))
        self.label_23.setText(_translate("MainWindow", "Degrees"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Position"))
        self.label_7.setText(_translate("MainWindow", "Px"))
        self.label_8.setText(_translate("MainWindow", "Pz "))
        self.label_9.setText(_translate("MainWindow", "Py"))
        self.label_24.setText(_translate("MainWindow", "Cm"))
        self.Return_box.setText(_translate("MainWindow", "Return Box"))
        self.forward.setText(_translate("MainWindow", "Forward"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.Inverse.setText(_translate("MainWindow", "Inverse"))
        self.Calc.setText(_translate("MainWindow", "Calc_The"))
        self.clear_row.setText(_translate("MainWindow", "Home"))
        self.label_5.setText(_translate("MainWindow", "MODE"))
        self.reset.setText(_translate("MainWindow", "Reset Home"))
        item = self.table_the.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_the.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_the.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_the.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table_the.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.table_the.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Theta 1"))
        item = self.table_the.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Theta 2"))
        item = self.table_the.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Theta 3"))
        __sortingEnabled = self.table_the.isSortingEnabled()
        self.table_the.setSortingEnabled(False)
        self.table_the.setSortingEnabled(__sortingEnabled)
        self.mode_manual.setText(_translate("MainWindow", "Manual"))
        self.mode_auto.setText(_translate("MainWindow", "Auto"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Position"))
        self.label_26.setText(_translate("MainWindow", "Px"))
        self.label_22.setText(_translate("MainWindow", "Py"))
        self.label_25.setText(_translate("MainWindow", "Pz "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Control"))
        self.set_robot.setText(_translate("MainWindow", "Set Robot"))
        self.start_cam.setText(_translate("MainWindow", "Start"))
        self.send_cam.setText(_translate("MainWindow", "Send Value Cam"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "FANUC CONTROLLING INTERFACE"))
        self.Menu.setText(_translate("MainWindow", "  Menu"))
        self.Setting.setText(_translate("MainWindow", "  Setting Connect"))
        self.Manual.setText(_translate("MainWindow", "  Manual Mode"))
        self.graph.setText(_translate("MainWindow", "  Response Graph"))
        self.Camera.setText(_translate("MainWindow", "  Camera"))
        self.Home.setText(_translate("MainWindow", "  Home"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
